const ActionTypes = {
  OPEN_ADD_DIALOG: 'OPEN_ADD_DIALOG',
  OPEN_EDIT_DIALOG: 'OPEN_EDIT_DIALOG',
  CLOSE_ADD_EDIT_DIALOG: 'CLOSE_EDIT_DIALOG',
  OPEN_DETAILS: 'OPEN_DETAILS',
  CLOSE_DETAILS: 'CLOSE_DETAILS',
  OPEN_DELETE_DIALOG: 'OPEN_DELETE_DIALOG',
  CLOSE_DELETE_DIALOG: 'CLOSE_DELETE_DIALOG',
  LOAD_MOVIES: 'LOAD_MOVIES',
  SET_FILTER_GENRE: 'SET_FILTER_GENRE',
  SET_SORT_BY: 'SET_SORT_BY'
};

export default ActionTypes;
