const ActionTypes = {
  OPEN_ADD_DIALOG: 'OPEN_ADD_DIALOG',
  OPEN_EDIT_DIALOG: 'OPEN_EDIT_DIALOG',
  CLOSE_ADD_EDIT_DIALOG: 'CLOSE_EDIT_DIALOG',
  OPEN_DETAILS: 'OPEN_DETAILS',
  CLOSE_DETAILS: 'CLOSE_DETAILS',
  OPEN_DELETE_DIALOG: 'OPEN_DELETE_DIALOG',
  CLOSE_DELETE_DIALOG: 'CLOSE_DELETE_DIALOG',
  LOAD_MOVIES: 'LOAD_MOVIES',
  LOAD_MOVIES_ERROR: 'LOAD_MOVIES_ERROR',
  LOAD_MOVIES_SUCCESS: 'LOAD_MOVIES_SUCCESS',
  SET_FILTER_GENRE: 'SET_FILTER_GENRE',
  SET_SORT_BY: 'SET_SORT_BY',
  DELETE_MOVIE: 'DELETE_MOVIE',
  DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
  DELETE_MOVIE_ERROR: 'DELETE_MOVIE_ERROR',
  CREATE_MOVIE: 'CREATE_MOVIE',
  CREATE_MOVIE_SUCCESS: 'CREATE_MOVIE_SUCCESS',
  CREATE_MOVIE_ERROR: 'CREATE_MOVIE_ERROR',
  EDIT_MOVIE: 'EDIT_MOVIE',
  EDIT_MOVIE_SUCCESS: 'EDIT_MOVIE_SUCCESS',
  EDIT_MOVIE_ERROR: 'EDIT_MOVIE_ERROR'
};

export default ActionTypes;
